# Generated by Django 2.2.16 on 2022-03-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0020_auto_20211213_2126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
    ]
